### ISSUE TITLE
Cannot download pretrained models for property prediction

### ISSUE THREAD

**Issue by jhshin-jlk** [kexinhuang12345/MolDesigner-Public#1]
Hi,

I've been trying to run this code on jupyter notebook, and it fails downloading the pretrained models.
I've found the download urls for the DTI models from the newly updated DeepPurpose, but I could not find the ones for the property prediction models.
Could you please check and update the links?

Thanks in advance,
JH

**Comment by kexinhuang12345** [comment]
Hi, JH, please see the updated version. Just pushed all the links in the repo.
